//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBcpService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BcpColumnFormat
    {
        public int Id { get; set; }
        public int BcpTableFormatId { get; set; }
        public string FromColumnName { get; set; }
        public string ToColumnName { get; set; }
        public string ToDataType { get; set; }
        public int Sequence { get; set; }
    
        public virtual BcpTableFormat BcpTableFormat { get; set; }
    }
}
